### PR TITLE
Few fixes to get `asyncipc` working with devel on windows

### LINKED ISSUE #43: AsyncIpc seems to be broken on devel for Windows
Found during the CI for nimlsp: https://github.com/PMunch/nimlsp/actions/runs/3807847256/jobs/6477921305#step:7:438

### PR DESCRIPTION
**Pull request by ire4ever1190**
Closes #43  

 - First fix was to make sure the object is `WideCString` first before casting to pointer so that we are actually accessing the data (On devel this calls a converter which returns the internal data)

 - I was running into a nil access error on ORC which I fixed by using the stdlib `getGlobalDispatcher()` instead

### CODE REVIEW

File: asynctools/asyncipc.nim [hunk 1]
```diff
@@ -267,7 +266,7 @@ elif defined(windows):
       interlockedOr(cast[ptr int32](data), 1)
 
     if register:
-      let p = getCurrentDispatcher()
+      let p = getGlobalDispatcher()
```
Comment (ire4ever1190) [inline asynctools/asyncipc.nim:269]: From what I can gather the use of `getCurrentDispatcher` was to access the `ioPort` handle? 1.6 (atleast I think 1.6) introduced [privateAccess](https://nim-lang.org/docs/importutils.html#privateAccess%2Ctypedesc) which allows us to get that handle without needing `HackDispatcher`.

If thats correct, should I make a follow up PR to replace `getCurrentDispatcher` with `getGlobalDispatcher`? (or even just do it in this PR)

Comment (Araq) [reply asynctools/asyncipc.nim:269]: Oh god no. Don't use `privateAccess` to hack your way into the standard library. Instead export the `ioPort` handle or an accessor proc.

Comment (ire4ever1190) [reply asynctools/asyncipc.nim:269]: Found [getIoHandler](https://nim-lang.org/docs/asyncdispatch.html#getIoHandler%2CPDispatcher) so no need in the end.

Does make me wonder what the point of `HackDispatcher` is then?

File: asynctools/asyncipc.nim [hunk 2]
```diff
@@ -130,6 +130,7 @@ elif defined(windows):
       ioPort: Handle
       handles: HashSet[AsyncFD]
     HackDispatcher = ptr HackDispatcherImpl
+    Dispatcher = HackDispatcher | PDispatcher
```
Comment (Araq) [inline asynctools/asyncipc.nim:133]: Too hacky and not required.

File: asynctools/asyncipc.nim [hunk 3]
```diff
@@ -322,7 +336,7 @@ elif defined(windows):
   template registerWaitableChange(ipc: AsyncIpcHandle, pcd, handleCallback) =
     let p = getCurrentDispatcher()
```
Comment (Araq) [inline asynctools/asyncipc.nim:337]:
```suggestion
    when declared(getIoHander):
      pcd.ioPort = p.getIoHandler()
    else:
      pcd.ioPort = cast[ptr Thing](p).ioPort # direct access
```
